In [47]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from utils import policy_evaluation, policy_iteration, value_iteration
from environment import GridWorld, generate_grid_world

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [33]:
n_rows = 5
n_cols = 5
n_states = n_rows*n_cols
n_actions = 4
n_rewards = 1

actions = {
    "up" : 0,
    "right" : 1,
    "down" : 2,
    "left": 3,
}




In [80]:
coord_A, coord_new_A,  reward_A = (1, 0), (1, 4), 10
coord_B, coord_new_B,  reward_B = (3, 0), (3, 2), 5
grid_world_1_param = {
    "n_rows": 5,
    "n_cols": 5,
    "step_reward": 0,
    "off_grid_reward" : -1,
    "special_transitions": {
        coord_A: (coord_new_A, reward_A),
        coord_B: (coord_new_B, reward_B),
    }
}

grid_world_1 = GridWorld(**grid_world_1_param)

In [81]:
policy = np.zeros((n_states, n_actions), dtype=np.float64)
probabilities, rewards  = grid_world_1.get_dynamics()
for s in range(n_states):
    for a in range(n_actions):
        policy[s, a] = 1/n_actions


In [82]:
result = policy_evaluation(policy, probabilities, rewards, gamma=0.9, eps=1e-5)
result.reshape((n_rows, n_cols))

array([[ 3.31283735,  8.79232751,  4.43054904,  5.32502981,  1.49497109],
       [ 1.52512462,  2.99531953,  2.25287586,  1.91013769,  0.54994357],
       [ 0.05420024,  0.74108211,  0.67574097,  0.36065232, -0.40073552],
       [-0.97030149, -0.43264951, -0.35231902, -0.58320368, -1.18074271],
       [-1.85444795, -1.34241664, -1.22673356, -1.42054648, -1.97287837]])

In [83]:
optimal_values = policy_iteration(probabilities, rewards, gamma=0.9, eps=1e-15)

In [84]:
optimal_values.reshape(n_rows, n_cols)

array([[21.97748527, 24.41942809, 21.97748528, 19.41942809, 17.47748528],
       [19.77973674, 21.97748528, 19.77973675, 17.80176308, 16.02158677],
       [17.80176307, 19.77973675, 17.80176308, 16.02158677, 14.41942809],
       [16.02158676, 17.80176308, 16.02158677, 14.41942809, 12.97748528],
       [14.41942809, 16.02158677, 14.41942809, 12.97748528, 11.67973675]])

In [85]:
value_iteration(probabilities, rewards, gamma=0.9, eps=1e-15).reshape(n_rows, n_cols)

array([[21.97748527, 24.41942809, 21.97748528, 19.41942809, 17.47748528],
       [19.77973674, 21.97748528, 19.77973675, 17.80176308, 16.02158677],
       [17.80176307, 19.77973675, 17.80176308, 16.02158677, 14.41942809],
       [16.02158676, 17.80176308, 16.02158677, 14.41942809, 12.97748528],
       [14.41942809, 16.02158677, 14.41942809, 12.97748528, 11.67973675]])

In [87]:
coord_A= (0, 0)
coord_B = (3, 3)
grid_world_2_param = {
    "n_rows": 4,
    "n_cols": 4,
    "step_reward": -1,
    "off_grid_reward" : 0,
    "special_transitions": {
        coord_A: (coord_A, 0),
        coord_B: (coord_B, 0),
    }
}

grid_world_2 = GridWorld(**grid_world_2_param)
probabilities, rewards  = grid_world_2.get_dynamics()

In [100]:
policy_iteration(probabilities, rewards, gamma=1, eps=1e-15).reshape(4, 4)

array([[ 0., -1., -2., -3.],
       [-1., -2., -3., -2.],
       [-2., -3., -2., -1.],
       [-3., -2., -1.,  0.]])

In [99]:
policy = np.ones((4*4, n_actions), dtype=np.float64)/n_actions
policy_evaluation(policy, probabilities, rewards, gamma=1, eps=1e-40).reshape(4, 4)

array([[  0., -14., -20., -22.],
       [-14., -18., -20., -20.],
       [-20., -20., -18., -14.],
       [-22., -20., -14.,   0.]])